import { GetOrdersApiResponse } from "@/lib/orders";
import { GetWarehousesApiResponse } from "@/lib/warehouses";

export const MOCK_WAREHOUSES: GetWarehousesApiResponse = {
  data: [
    { warehouseNumber: "101", warehouseName: "Oslo Sentrallager", warehouseId: "WH-101" },
    { warehouseNumber: "102", warehouseName: "Bergen Regionlager", warehouseId: "WH-102" },
    { warehouseNumber: "103", warehouseName: "Trondheim Distribusjon", warehouseId: "WH-103" },
  ],
};

const today = new Date();
function daysAgo(n: number) {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const MOCK_ORDERS: GetOrdersApiResponse = {
  data: [
    {
      orderId: 1001,
      orderNumber: "ORD-2026-1001",
      date: daysAgo(2),
      customerNumber: "169999",
      customerRef: "REF-A100",
      customerOrderRef: "KO-55001",
      warehouseId: "WH-101",
      warehouseNumber: "101",
      warehouseName: "Oslo Sentrallager",
      sum: 14850,
      orderAmendedDate: daysAgo(1),
      orderLines: [
        {
          orderLineNumber: 1,
          itemId: 501,
          itemName: "Kontorpapir A4 500 ark",
          itemNumber: "KP-A4-500",
          quantity: 10,
          unit: "stk",
          netPrice: 85,
          lineStatus: 300,
          lineSum: 850,
          orderLineAmendedDate: daysAgo(1),
        },
        {
          orderLineNumber: 2,
          itemId: 502,
          itemName: "Blekkpatron svart HP 301",
          itemNumber: "BP-HP301-S",
          quantity: 5,
          unit: "stk",
          netPrice: 280,
          lineStatus: 300,
          lineSum: 1400,
          orderLineAmendedDate: daysAgo(1),
        },
        {
          orderLineNumber: 3,
          itemId: 503,
          itemName: "Perm A4 bred rød",
          itemNumber: "PM-A4-RD",
          quantity: 20,
          unit: "stk",
          netPrice: 45,
          lineStatus: 500,
          lineSum: 900,
          orderLineAmendedDate: daysAgo(0),
        },
      ],
    },
    {
      orderId: 1002,
      orderNumber: "ORD-2026-1002",
      date: daysAgo(5),
      customerNumber: "169999",
      customerRef: "REF-B200",
      customerOrderRef: "KO-55002",
      warehouseId: "WH-102",
      warehouseNumber: "102",
      warehouseName: "Bergen Regionlager",
      sum: 6200,
      orderAmendedDate: daysAgo(3),
      orderLines: [
        {
          orderLineNumber: 1,
          itemId: 601,
          itemName: "Whiteboard 120x90 cm",
          itemNumber: "WB-120-90",
          quantity: 2,
          unit: "stk",
          netPrice: 1950,
          lineStatus: 600,
          lineSum: 3900,
          orderLineAmendedDate: daysAgo(3),
        },
        {
          orderLineNumber: 2,
          itemId: 602,
          itemName: "Whiteboard-marker sett 4 farger",
          itemNumber: "WBM-4FK",
          quantity: 10,
          unit: "sett",
          netPrice: 89,
          lineStatus: 600,
          lineSum: 890,
          orderLineAmendedDate: daysAgo(3),
        },
      ],
    },
    {
      orderId: 1003,
      orderNumber: "ORD-2026-1003",
      date: daysAgo(10),
      customerNumber: "169999",
      customerRef: "REF-C300",
      customerOrderRef: "KO-55003",
      warehouseId: "WH-101",
      warehouseNumber: "101",
      warehouseName: "Oslo Sentrallager",
      sum: 32500,
      orderAmendedDate: daysAgo(7),
      orderLines: [
        {
          orderLineNumber: 1,
          itemId: 701,
          itemName: "Ergonomisk kontorstol sort",
          itemNumber: "ST-ERG-SRT",
          quantity: 5,
          unit: "stk",
          netPrice: 4200,
          lineStatus: 700,
          lineSum: 21000,
          orderLineAmendedDate: daysAgo(7),
        },
        {
          orderLineNumber: 2,
          itemId: 702,
          itemName: "Hev-senk skrivebord 160x80",
          itemNumber: "SD-HS-1680",
          quantity: 3,
          unit: "stk",
          netPrice: 3800,
          lineStatus: 700,
          lineSum: 11400,
          orderLineAmendedDate: daysAgo(7),
        },
      ],
    },
    {
      orderId: 1004,
      orderNumber: "ORD-2026-1004",
      date: daysAgo(1),
      customerNumber: "169999",
      customerRef: "REF-D400",
      customerOrderRef: "KO-55004",
      warehouseId: "WH-103",
      warehouseNumber: "103",
      warehouseName: "Trondheim Distribusjon",
      sum: 4750,
      orderAmendedDate: daysAgo(0),
      orderLines: [
        {
          orderLineNumber: 1,
          itemId: 801,
          itemName: "Kaffemaskin Jura E8",
          itemNumber: "KM-JURA-E8",
          quantity: 1,
          unit: "stk",
          netPrice: 4750,
          lineStatus: 200,
          lineSum: 4750,
          orderLineAmendedDate: daysAgo(0),
        },
      ],
    },
  ],
  meta: {
    page: 1,
    pageSize: 25,
    totalPages: 1,
    totalItems: 4,
  },
};
